<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="David Sawyer" />


<title>Project1</title>

<script src="site_libs/jquery-1.12.4/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.0/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="site_libs/datatables-binding-0.4/datatables.js"></script>
<link href="site_libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="site_libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="site_libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">David Sawyer</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="About.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="HousingPrices.html">Regressing on Housing Prices</a>
    </li>
    <li>
      <a href="MachineLearning.html">Machine Learning Competition</a>
    </li>
    <li>
      <a href="Genomes.html">Genomesequencing Grades</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Project1</h1>
<h4 class="author"><em>David Sawyer</em></h4>
<h4 class="date"><em>3/13/2017</em></h4>

</div>


<pre class="r"><code>library(DT)
library(ggplot2)
library(MASS)
library(car)</code></pre>
<pre class="r"><code>HP &lt;- read.delim(&#39;http://ww2.amstat.org/publications/jse/datasets/homes76.dat.txt&#39;, header = TRUE)
HP &lt;- data.frame(HP[2], HP[3], HP[4], HP[5], HP[6], HP[8], HP[9], HP[11], HP[12], HP[13], HP[14])
names(HP) &lt;- c(&#39;price&#39;, &#39;size&#39;, &#39;lot&#39;, &#39;bath&#39;, &#39;bed&#39;, &#39;year&#39;, &#39;age&#39;, &#39;garage&#39;, &#39;status&#39;, &#39;active&#39;, &#39;elem&#39;)
datatable(HP)</code></pre>
<div id="htmlwidget-6119c96db35c4a6471d5" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-6119c96db35c4a6471d5">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76"],[388,450,386,350,155.5,220,239.5,207,269.9,238.8,359.9,249.7,265,349,319,339,283,275,299.9,277,299,185,232,214.9,195,256,269.7,330,249.9,279.9,325,259.9,324.5,359.9,252.5,269,235,256.5,319.9,355,285,242,197,281.8,259,189.5,339.9,297,295,222.5,199,385.5,230,285,243,217,259.9,349.5,345,336,333.75,340,345,374.5,236.5,350,270,299,285,255,259,249.9,215,435,274.9,349.5],[2.18,2.054,2.112,1.442,1.8,1.965,1.8,2.254,1.922,1.92,2.2,1.868,1.875,2,1.855,1.928,1.98,1.528,1.882,1.44,1.994,1.86,2.031,1.868,2.112,1.974,2.1,1.894,1.804,2.01,1.661,1.708,1.8,1.968,1.888,1.8,1.712,2.2,1.92,2.129,2.235,2.279,1.85,1.886,2.08,1.906,2.048,2.106,2.028,1.794,2.016,1.904,2.234,2.269,1.81,1.875,1.683,2.08,2.126,2.126,2.126,2.126,2.126,1.712,1.95,2.02,2.053,1.743,1.878,1.9,2.208,2.081,2.044,2.253,1.861,2.896],[4,5,5,6,1,5,4,4,4,5,5,4,4,5,4,5,4,3,3,3,8,4,4,5,4,4,4,2,5,5,4,4,2,3,2,3,5,4,7,5,7,5,3,4,2,3,5,4,4,4,3,4,3,3,4,4,5,4,1,1,1,1,1,5,4,7,3,3,5,4,4,5,1,11,4,4],[3,3,2,1,2,2,1.1,2,2.1,2.1,2,2,2.1,2,2,3,3,2.1,2.1,2,3,2,2,2,2,2,2,2,2,2,1.1,2,2.1,3,2,3,1,2.1,2.1,2,3.1,2.1,2,2,2,2.1,2,2.1,3,2,2,1.1,3,3.1,3,2,2.1,2.1,3.1,3.1,3.1,3.1,3.1,1.1,3,2,2.1,2,2.1,2,3,2.1,1.1,2,2,3],[4,4,4,2,4,3,4,4,4,3,3,4,3,3,4,3,4,3,3,3,2,5,4,4,3,3,4,3,3,3,3,4,3,3,6,5,3,3,3,3,4,4,4,3,4,3,2,3,5,3,5,3,4,4,3,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,4,4,3,4,5],[1940,1957,1955,1956,1994,1940,1958,1961,1965,1968,1970,1965,1979,1997,1925,1972,1971,1975,1976,1948,2005,1953,1950,1966,1966,1961,1969,1950,1960,1969,1974,1937,2000,1980,1920,1947,1948,1966,2004,2003,1975,1949,1964,2005,1969,1975,1993,1995,1992,1960,1963,1919,1972,1905,1961,1961,1979,2005,2005,2005,2005,2005,2005,1908,1966,1976,1977,1988,1975,1980,1979,1970,1936,1979,1995,1979],[-3,-1.3,-1.5,-1.4,2.4,-3,-1.2,-0.9,-0.5,-0.2,0,-0.5,0.9,2.7,-4.5,0.2,0.1,0.5,0.6,-2.2,3.5,-1.7,-2,-0.4,-0.4,-0.9,-0.1,-2,-1,-0.1,0.4,-3.3,3,1,-5,-2.3,-2.2,-0.4,3.4,3.3,0.5,-2.1,-0.6,3.5,-0.1,0.5,2.3,2.5,2.2,-1,-0.7,-5.1,0.2,-6.5,-0.9,-0.9,0.9,3.5,3.5,3.5,3.5,3.5,3.5,-6.2,-0.4,0.6,0.7,1.8,0.5,1,0.9,0,-3.4,0.9,2.5,0.9],[0,2,2,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,3,0,0,2,2,2,2,1,2,2,2,0,1,2,0,0,1,2,2,2,2,1,1,2,2,0,3,2,2,0,1,1,2,0,2,0,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,0,2,2,2],["sld","sld","sld","act","sld","sld","act","sld","act","sld","act","sld","sld","pen","sld","act","act","act","act","act","pen","sld","sld","sld","sld","sld","act","sld","pen","pen","act","act","pen","act","sld","sld","sld","sld","act","pen","act","sld","sld","sld","pen","sld","pen","sld","sld","sld","pen","sld","sld","sld","sld","sld","act","act","act","pen","act","sld","sld","pen","pen","pen","act","act","act","sld","act","sld","sld","sld","act","act"],[0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,1,0,1,0,0,0,1,1],["edison","edison","edison","adams","adams","adams","parker","parker","parker","parker","edge","edge","edge","edge","harris","edge","edge","edge","edge","edison","parker","parker","parker","edge","edge","harris","parker","edison","edge","edison","crest","crest","harris","harris","edison","edge","edison","edge","parker","parker","crest","parker","edge","edison","edge","edge","edge","edge","edge","crest","edge","edison","edge","edison","edge","edge","harris","harris","harris","harris","harris","harris","harris","edison","edge","harris","edge","harris","crest","parker","parker","harris","parker","edge","parker","crest"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>price<\/th>\n      <th>size<\/th>\n      <th>lot<\/th>\n      <th>bath<\/th>\n      <th>bed<\/th>\n      <th>year<\/th>\n      <th>age<\/th>\n      <th>garage<\/th>\n      <th>status<\/th>\n      <th>active<\/th>\n      <th>elem<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5,6,7,8,10]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<div id="exploration-of-data" class="section level2 unnumbered">
<h2>Exploration of data</h2>
<p>On its own <code>age</code> ( <code>price</code> ~ <code>age</code>) seems to be not important given its low t-value and high p-value, but from the article we no this is not the case. This must mean that <code>age</code><span class="math inline">\(^2\)</span> might change that or it is important in context with other variables. Also, an open status in a simple model (<code>price</code> ~ <code>status</code>) is not significant factor, but is also something that becomes significant in the greater model when added to a model with several barriers. This follows with active which is just a dummy variable for when <code>status</code> equals open so it makes sense. When adding everything to one model and add <code>age</code><span class="math inline">\(^2\)</span> things change. <code>age</code><span class="math inline">\(^2\)</span> is significant.</p>
</div>
<div id="what-are-the-units-for-price-and-size" class="section level2">
<h2>What are the units for <code>price</code> and <code>size</code>?</h2>
<pre class="r"><code>mod.hi &lt;- lm(price ~ ., data = HP)
mod.low &lt;- lm(price ~ 1, data = HP )
mod.fs &lt;- stepAIC(mod.low, scope = list(lower = mod.low, upper = mod.hi), direction = &quot;forward&quot;)</code></pre>
<pre><code>## Start:  AIC=624.17
## price ~ 1
## 
##          Df Sum of Sq    RSS    AIC
## + elem    5     60570 212433 615.11
## + garage  1     35065 237938 615.73
## + bed     1     22361 250641 619.68
## + lot     1     16284 256718 621.50
## + status  2     20951 252052 622.11
## + size    1     11078 261925 623.03
## + active  1      9219 263784 623.56
## + bath    1      8328 264674 623.82
## &lt;none&gt;                273002 624.17
## + year    1      6485 266517 624.35
## + age     1      6485 266517 624.35
## 
## Step:  AIC=615.11
## price ~ elem
## 
##          Df Sum of Sq    RSS    AIC
## + garage  1     40716 171717 600.94
## + lot     1     35860 176573 603.06
## + status  2     25695 186738 609.31
## + bed     1     19964 192469 609.61
## + age     1     17610 194823 610.53
## + year    1     17610 194823 610.53
## + active  1     14549 197884 611.72
## + size    1     12382 200051 612.55
## &lt;none&gt;                212433 615.11
## + bath    1      4284 208149 615.56
## 
## Step:  AIC=600.94
## price ~ elem + garage
## 
##          Df Sum of Sq    RSS    AIC
## + lot     1   18261.9 153455 594.39
## + size    1    7010.3 164707 599.77
## + active  1    5486.8 166230 600.47
## &lt;none&gt;                171717 600.94
## + bed     1    4075.2 167642 601.11
## + status  2    8034.8 163682 601.30
## + bath    1    1625.2 170092 602.22
## + year    1    1183.4 170534 602.41
## + age     1    1183.4 170534 602.41
## 
## Step:  AIC=594.39
## price ~ elem + garage + lot
## 
##          Df Sum of Sq    RSS    AIC
## + active  1    7593.8 145861 592.54
## + size    1    7299.1 146156 592.69
## + status  2    9400.3 144055 593.59
## + bath    1    4022.6 149433 594.37
## &lt;none&gt;                153455 594.39
## + age     1    2939.1 150516 594.92
## + year    1    2939.1 150516 594.92
## + bed     1    1311.2 152144 595.74
## 
## Step:  AIC=592.54
## price ~ elem + garage + lot + active
## 
##          Df Sum of Sq    RSS    AIC
## + size    1   11949.1 133912 588.04
## + bath    1    4183.5 141678 592.32
## &lt;none&gt;                145861 592.54
## + year    1    2772.6 143089 593.08
## + age     1    2772.6 143089 593.08
## + status  1    1806.5 144055 593.59
## + bed     1     949.5 144912 594.04
## 
## Step:  AIC=588.04
## price ~ elem + garage + lot + active + size
## 
##          Df Sum of Sq    RSS    AIC
## + bed     1    4696.1 129216 587.33
## &lt;none&gt;                133912 588.04
## + status  1    3261.0 130651 588.17
## + year    1    1895.9 132016 588.96
## + age     1    1895.9 132016 588.96
## + bath    1     211.9 133700 589.92
## 
## Step:  AIC=587.33
## price ~ elem + garage + lot + active + size + bed
## 
##          Df Sum of Sq    RSS    AIC
## &lt;none&gt;                129216 587.33
## + status  1   2712.28 126504 587.71
## + year    1    723.98 128492 588.90
## + age     1    723.98 128492 588.90
## + bath    1    551.18 128665 589.00</code></pre>
<pre class="r"><code>mod.be &lt;- stepAIC(mod.hi, scope = list(lower = mod.low,upper = mod.hi), direction = &quot;backward&quot;)</code></pre>
<pre><code>## Start:  AIC=591.14
## price ~ size + lot + bath + bed + year + age + garage + status + 
##     active + elem
## 
## 
## Step:  AIC=591.14
## price ~ size + lot + bath + bed + year + age + garage + status + 
##     elem
## 
## 
## Step:  AIC=591.14
## price ~ size + lot + bath + bed + year + garage + status + elem
## 
##          Df Sum of Sq    RSS    AIC
## - year    1       295 125846 589.32
## - bath    1       436 125986 589.40
## - garage  1      1338 126889 589.95
## &lt;none&gt;                125551 591.14
## - bed     1      3541 129092 591.25
## - status  2     14277 139828 595.33
## - size    1     11116 136666 595.59
## - lot     1     16863 142414 598.72
## - elem    5     72614 198165 615.83
## 
## Step:  AIC=589.32
## price ~ size + lot + bath + bed + garage + status + elem
## 
##          Df Sum of Sq    RSS    AIC
## - bath    1       658 126504 587.71
## - garage  1      2066 127912 588.56
## &lt;none&gt;                125846 589.32
## - bed     1      4500 130346 589.99
## - status  2     14556 140401 593.64
## - size    1     11370 137216 593.89
## - lot     1     16592 142437 596.73
## - elem    5     78085 203930 616.00
## 
## Step:  AIC=587.71
## price ~ size + lot + bed + garage + status + elem
## 
##          Df Sum of Sq    RSS    AIC
## - garage  1      2432 128936 587.16
## &lt;none&gt;                126504 587.71
## - bed     1      4147 130651 588.17
## - status  2     15172 141676 592.32
## - lot     1     15997 142501 594.76
## - size    1     16863 143367 595.22
## - elem    5     80040 206544 614.97
## 
## Step:  AIC=587.16
## price ~ size + lot + bed + status + elem
## 
##          Df Sum of Sq    RSS    AIC
## &lt;none&gt;                128936 587.16
## - bed     1      7689 136625 589.56
## - status  2     22758 151694 595.52
## - lot     1     18948 147883 595.58
## - size    1     23305 152240 597.79
## - elem    5     80234 209170 613.93</code></pre>
<p>The units of <code>price</code> on <code>size</code> is in units of 1000 square feet, so 2400 square feet is represented as 2.4.</p>
<p>The backwards method has a better model because it has a lower AIC. The backwards AIC = 587.16 and the forward AIC = 587.33.</p>
</div>
<div id="create-mod1-and-what-would-be-you-change" class="section level2">
<h2>Create mod1 and what would be you change?</h2>
<pre class="r"><code>mod1 &lt;- lm(price ~ . - status - year, data = HP)

summary(mod1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ . - status - year, data = HP)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -87.265 -27.217  -0.222  30.125  95.583 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   88.144     57.780   1.526  0.13214   
## size          69.782     30.934   2.256  0.02756 * 
## lot           10.750      3.667   2.932  0.00469 **
## bath           4.615     11.748   0.393  0.69575   
## bed          -12.459      9.120  -1.366  0.17676   
## age            1.626      3.324   0.489  0.62643   
## garage        10.053      9.261   1.086  0.28182   
## active        30.874     12.902   2.393  0.01971 * 
## elemcrest      4.809     34.067   0.141  0.88819   
## elemedge       7.466     29.050   0.257  0.79802   
## elemedison    87.195     30.810   2.830  0.00624 **
## elemharris    53.786     30.629   1.756  0.08394 . 
## elemparker   -11.904     30.009  -0.397  0.69296   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 45.11 on 63 degrees of freedom
## Multiple R-squared:  0.5305, Adjusted R-squared:  0.4411 
## F-statistic: 5.932 on 12 and 63 DF,  p-value: 8.906e-07</code></pre>
<pre class="r"><code>res &lt;- car::residualPlots(mod1)</code></pre>
<p><img src="HousingPrices_files/figure-html/mod1-1.png" width="1152" /></p>
<pre class="r"><code>res</code></pre>
<pre><code>##            Test stat Pr(&gt;|t|)
## size           0.303    0.763
## lot            1.979    0.052
## bath           2.376    0.021
## bed            1.011    0.316
## age            2.316    0.024
## garage         0.813    0.419
## active        -2.016    0.048
## elem              NA       NA
## Tukey test     0.333    0.739</code></pre>
<p>Given the residual plots, size and lot looks linear while it seems that bath, lot, bed, and age seem to have a non-linear form. I would probably attempt to create a sqared term for those terms to see if it boosts the adjusted <span class="math inline">\(R^2\)</span> term, which is `r 0.4410564. I would also try interaction terms with the terms that seem non-linear to see which ones are a better fit to the data.</p>
</div>
<div id="create-mod2" class="section level2">
<h2>Create mod2</h2>
<pre class="r"><code>mod2 &lt;- lm(price ~ . - status - year + bath:bed + I(age ^ 2), HP)
summary(mod2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ . - status - year + bath:bed + I(age^2), 
##     data = HP)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -83.284 -22.628  -0.066  27.790 111.323 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 308.7738   118.9553   2.596  0.01181 * 
## size         58.7689    29.2569   2.009  0.04900 * 
## lot          10.3619     3.5731   2.900  0.00518 **
## bath        -98.7362    47.9507  -2.059  0.04376 * 
## bed         -77.4817    32.3252  -2.397  0.01961 * 
## age           3.7771     3.2371   1.167  0.24784   
## garage       10.6773     8.7030   1.227  0.22460   
## active       30.3572    12.2685   2.474  0.01614 * 
## elemcrest    20.0071    32.4456   0.617  0.53977   
## elemedge     28.8890    28.2176   1.024  0.30998   
## elemedison   88.1039    29.7429   2.962  0.00435 **
## elemharris   69.1235    30.3032   2.281  0.02605 * 
## elemparker   14.9554    30.7470   0.486  0.62842   
## I(age^2)      1.8236     0.7571   2.409  0.01905 * 
## bath:bed     29.6573    13.6582   2.171  0.03380 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 42.37 on 61 degrees of freedom
## Multiple R-squared:  0.5989, Adjusted R-squared:  0.5068 
## F-statistic: 6.505 on 14 and 61 DF,  p-value: 8.906e-08</code></pre>
<pre class="r"><code>summary(mod2)$adj.r.squared</code></pre>
<pre><code>## [1] 0.5068237</code></pre>
<p><span class="math display">\[R^2 = 0.5068237\]</span></p>
</div>
<div id="create-mod3" class="section level2">
<h2>Create mod3</h2>
<pre class="r"><code>mod3 &lt;- update(mod2, . ~ . -elem + I(elem == &quot;harris&quot;) + I(elem == &quot;edison&quot;))
#mod3 &lt;- lm(price )
mod3</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ size + lot + bath + bed + age + garage + 
##     active + I(age^2) + I(elem == &quot;harris&quot;) + I(elem == &quot;edison&quot;) + 
##     bath:bed, data = HP)
## 
## Coefficients:
##             (Intercept)                     size                      lot  
##                 332.478                   56.719                    9.917  
##                    bath                      bed                      age  
##                 -98.156                  -78.910                    3.301  
##                  garage                   active                 I(age^2)  
##                  13.119                   27.424                    1.641  
## I(elem == &quot;harris&quot;)TRUE  I(elem == &quot;edison&quot;)TRUE                 bath:bed  
##                  47.273                   67.062                   30.390</code></pre>
<pre class="r"><code>summary(mod3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ size + lot + bath + bed + age + garage + 
##     active + I(age^2) + I(elem == &quot;harris&quot;) + I(elem == &quot;edison&quot;) + 
##     bath:bed, data = HP)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -81.310 -26.101  -1.337  27.236 105.083 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             332.4781   106.5992   3.119 0.002720 ** 
## size                     56.7190    27.9738   2.028 0.046772 *  
## lot                       9.9168     3.4379   2.885 0.005335 ** 
## bath                    -98.1564    42.6665  -2.301 0.024686 *  
## bed                     -78.9099    27.7519  -2.843 0.005985 ** 
## age                       3.3014     3.1695   1.042 0.301507    
## garage                   13.1185     8.2846   1.583 0.118239    
## active                   27.4236    10.9885   2.496 0.015160 *  
## I(age^2)                  1.6413     0.7333   2.238 0.028683 *  
## I(elem == &quot;harris&quot;)TRUE  47.2732    14.8443   3.185 0.002240 ** 
## I(elem == &quot;edison&quot;)TRUE  67.0619    16.8220   3.987 0.000175 ***
## bath:bed                 30.3901    11.8781   2.559 0.012889 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 41.91 on 64 degrees of freedom
## Multiple R-squared:  0.5883, Adjusted R-squared:  0.5175 
## F-statistic: 8.314 on 11 and 64 DF,  p-value: 7.698e-09</code></pre>
<pre class="r"><code>anova(mod3, mod2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: price ~ size + lot + bath + bed + age + garage + active + I(age^2) + 
##     I(elem == &quot;harris&quot;) + I(elem == &quot;edison&quot;) + bath:bed
## Model 2: price ~ (size + lot + bath + bed + year + age + garage + status + 
##     active + elem) - status - year + bath:bed + I(age^2)
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1     64 112395                           
## 2     61 109506  3    2889.6 0.5365  0.659</code></pre>
<p>Yes, the p-value is NA, 0.6590107 <span class="math display">\[R^2 = 0.5175377\]</span> P - value of this F-test is saying that there is a NA, 0.6590107 chance that the models fit the data equally. So we can drop the three indicators because we fail to reject the null hypothesis that they are equal to 0.</p>
</div>
<div id="mse-training" class="section level2">
<h2>MSE Training</h2>
<pre class="r"><code>mean(resid(mod.fs)^2)</code></pre>
<pre><code>## [1] 1700.212</code></pre>
<pre class="r"><code>mean(resid(mod.be)^2)</code></pre>
<pre><code>## [1] 1696.523</code></pre>
<pre class="r"><code>mean(resid(mod2)^2)</code></pre>
<pre><code>## [1] 1440.867</code></pre>
<pre class="r"><code>mean(resid(mod3)^2)</code></pre>
<pre><code>## [1] 1478.887</code></pre>
<p>mod2 has the lowest MSE with 1440.8665899. I can’t be sure, but I do know that given what we have found with the F-Test for mod3 it might be score higher than mod3. But, we have very little data and so the F-Test may be faulty. I would stick with mod3 and see how things turned out and adjust if it turns out that it is incorrect.</p>
</div>
<div id="mod3-prediction-interval" class="section level2">
<h2>Mod3 Prediction Interval</h2>
<pre class="r"><code>predict(mod3, newdata = data.frame(size = 1.879, lot = 4, bath = 2.1, bed = 3, garage = 2, active = 1 , age = .5, elem = &#39;parker&#39;), level = .95, interval = &#39;predict&#39;)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 283.0415 197.0626 369.0205</code></pre>
</div>
<div id="extra-credit" class="section level2">
<h2>Extra Credit</h2>
<pre class="r"><code>library(effects)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;carData&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:car&#39;:
## 
##     Guyer, UN, Vocab</code></pre>
<pre><code>## lattice theme set by effectsTheme()
## See ?effectsTheme for details.</code></pre>
<pre class="r"><code>plot(allEffects(mod2))</code></pre>
<p><img src="HousingPrices_files/figure-html/ec-1.png" width="672" /></p>
<pre class="r"><code>plot(effect(&quot;bath*bed&quot;, mod2))</code></pre>
<p><img src="HousingPrices_files/figure-html/ec-2.png" width="672" /></p>
<pre class="r"><code>plot(effect(&quot;bath*bed&quot;, mod2, xlevels=list(bed=2:5)))</code></pre>
<p><img src="HousingPrices_files/figure-html/ec-3.png" width="672" /></p>
<pre class="r"><code>plot(effect(&quot;bath*bed&quot;, mod2, xlevels=list(bath=1:3)))</code></pre>
<p><img src="HousingPrices_files/figure-html/ec-4.png" width="672" /></p>
<p>The first set of graphs is displaying the scatter plots of the indicators. THe second set of graphs is showing the slope of mod2 when bed equals 2 thorugh 5. The third modle is showing the slope for the bath*bed term as bed is set equal to the values 1 through 3.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
